name: Update Data

on:
  schedule:
    - cron: '0 */6 * * *'   # every 6 hours
    - cron: '0 0 * * *'     # daily
    - cron: '0 0 * * 0'     # weekly
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Build JSON data
        run: npm run build
      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/**/*.json
          git commit -m "chore: update data [skip ci]" || echo "No changes"
          git push
